# Generated by Django 4.1.1 on 2022-09-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpi_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="kpimessage", name="id",),
        migrations.AlterField(
            model_name="kpimessage",
            name="asset_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="KpiResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("result", models.CharField(max_length=50)),
                (
                    "message_asset_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi_app.kpimessage",
                    ),
                ),
                (
                    "message_kpi_expression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi_app.kpiinformation",
                    ),
                ),
            ],
        ),
    ]
